In [5]:
#1. Dadas 2 matrices con dimensiones similares, ¿cómo obtener una salida
#de matriz en la que cada elemento es una suma de elementos de las 2
#matrices? (solo puede usar numpy como librería, si realiza la matriz
#con otro paquete el ejercicio no es válido)

import numpy as np

a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])

c = np.add(a, b)
print(c)

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [6]:
#2. Cree una matriz de identidad de dimensión 4.

import numpy as np

identity_matrix = np.identity(4)
print(identity_matrix)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [7]:
#3. Convierte una matriz numpy binaria (que contiene solo 0 y 1) en una matriz numpy booleana.

import numpy as np

binary_matrix = np.array([[0, 1, 1], [1, 0, 1], [0, 0, 1]])
boolean_matrix = np.asarray(binary_matrix, dtype=bool)

print(boolean_matrix)

[[False  True  True]
 [ True False  True]
 [False False  True]]


In [8]:
#4. Genere una secuencia de números en forma de matriz numpy de 0 a 100 con espacios de 2 números, por ejemplo: 0, 2, 4 ...


import numpy as np

sequence = np.arange(start=0, stop=101, step=2)
print(sequence)


[  0   2   4   6   8  10  12  14  16  18  20  22  24  26  28  30  32  34
  36  38  40  42  44  46  48  50  52  54  56  58  60  62  64  66  68  70
  72  74  76  78  80  82  84  86  88  90  92  94  96  98 100]
